channels:
  - conda-forge
  - terradue
dependencies:
  - python=3.8
  - numpy
  - jupyter-server-proxy
  - code-server >=3.2
  - pystac
  - mamba>=0.22.1 
  - pip
  - cwltool
  - nodejs
  - ipyleaflet
  - localtileserver
  - pip:
    - rio_color
    - snuggs
